# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './settings_main_widgets.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1188, 711)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_global_contextmenu_show = QtWidgets.QCheckBox(Dialog)
        self.cb_global_contextmenu_show.setObjectName("cb_global_contextmenu_show")
        self.horizontalLayout.addWidget(self.cb_global_contextmenu_show)
        self.cb_global_contextmenu_with_styling = QtWidgets.QCheckBox(Dialog)
        self.cb_global_contextmenu_with_styling.setObjectName("cb_global_contextmenu_with_styling")
        self.horizontalLayout.addWidget(self.cb_global_contextmenu_with_styling)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pb_global_multibutton_show = QtWidgets.QPushButton(Dialog)
        self.pb_global_multibutton_show.setObjectName("pb_global_multibutton_show")
        self.horizontalLayout.addWidget(self.pb_global_multibutton_show)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cb_classes_to_styling = QtWidgets.QCheckBox(Dialog)
        self.cb_classes_to_styling.setObjectName("cb_classes_to_styling")
        self.horizontalLayout.addWidget(self.cb_classes_to_styling)
        self.pb_more = QtWidgets.QPushButton(Dialog)
        self.pb_more.setObjectName("pb_more")
        self.horizontalLayout.addWidget(self.pb_more)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.ql_active = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ql_active.setFont(font)
        self.ql_active.setObjectName("ql_active")
        self.verticalLayout.addWidget(self.ql_active)
        self.hl_active = QtWidgets.QHBoxLayout()
        self.hl_active.setObjectName("hl_active")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_add = QtWidgets.QPushButton(Dialog)
        self.pb_add.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_add.sizePolicy().hasHeightForWidth())
        self.pb_add.setSizePolicy(sizePolicy)
        self.pb_add.setAutoDefault(True)
        self.pb_add.setObjectName("pb_add")
        self.verticalLayout_2.addWidget(self.pb_add)
        self.pb_modify_active = QtWidgets.QPushButton(Dialog)
        self.pb_modify_active.setObjectName("pb_modify_active")
        self.verticalLayout_2.addWidget(self.pb_modify_active)
        self.pb_deactivate = QtWidgets.QPushButton(Dialog)
        self.pb_deactivate.setObjectName("pb_deactivate")
        self.verticalLayout_2.addWidget(self.pb_deactivate)
        self.pb_delete_from_active = QtWidgets.QPushButton(Dialog)
        self.pb_delete_from_active.setObjectName("pb_delete_from_active")
        self.verticalLayout_2.addWidget(self.pb_delete_from_active)
        self.hl_active.addLayout(self.verticalLayout_2)
        self.tw_active = QtWidgets.QTableWidget(Dialog)
        self.tw_active.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tw_active.setObjectName("tw_active")
        self.tw_active.setColumnCount(0)
        self.tw_active.setRowCount(0)
        self.hl_active.addWidget(self.tw_active)
        self.verticalLayout.addLayout(self.hl_active)
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.ql_inactive = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ql_inactive.setFont(font)
        self.ql_inactive.setTextFormat(QtCore.Qt.PlainText)
        self.ql_inactive.setObjectName("ql_inactive")
        self.verticalLayout.addWidget(self.ql_inactive)
        self.hl_inactive = QtWidgets.QHBoxLayout()
        self.hl_inactive.setObjectName("hl_inactive")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_activate = QtWidgets.QPushButton(Dialog)
        self.pb_activate.setObjectName("pb_activate")
        self.verticalLayout_3.addWidget(self.pb_activate)
        self.pb_modify_inactive = QtWidgets.QPushButton(Dialog)
        self.pb_modify_inactive.setObjectName("pb_modify_inactive")
        self.verticalLayout_3.addWidget(self.pb_modify_inactive)
        self.pb_delete_from_inactive = QtWidgets.QPushButton(Dialog)
        self.pb_delete_from_inactive.setObjectName("pb_delete_from_inactive")
        self.verticalLayout_3.addWidget(self.pb_delete_from_inactive)
        self.hl_inactive.addLayout(self.verticalLayout_3)
        self.tw_inactive = QtWidgets.QTableWidget(Dialog)
        self.tw_inactive.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tw_inactive.setObjectName("tw_inactive")
        self.tw_inactive.setColumnCount(0)
        self.tw_inactive.setRowCount(0)
        self.hl_inactive.addWidget(self.tw_inactive)
        self.verticalLayout.addLayout(self.hl_inactive)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "General config:"))
        self.cb_global_contextmenu_show.setText(_translate("Dialog", "show entries in contextmenu"))
        self.cb_global_contextmenu_with_styling.setText(_translate("Dialog", "(context) menu styling"))
        self.label_2.setText(_translate("Dialog", "Key for multi-button"))
        self.pb_global_multibutton_show.setText(_translate("Dialog", "click to set"))
        self.cb_classes_to_styling.setText(_translate("Dialog", "Write Link to CSS into every Template"))
        self.pb_more.setText(_translate("Dialog", "more"))
        self.ql_active.setText(_translate("Dialog", "Active Buttons/Entries:"))
        self.pb_add.setText(_translate("Dialog", "Add entry"))
        self.pb_modify_active.setText(_translate("Dialog", "Modify"))
        self.pb_deactivate.setText(_translate("Dialog", "Deactivate"))
        self.pb_delete_from_active.setText(_translate("Dialog", "Delete"))
        self.ql_inactive.setText(_translate("Dialog", "Inactive Buttons/Entries:"))
        self.pb_activate.setText(_translate("Dialog", "Activate"))
        self.pb_modify_inactive.setText(_translate("Dialog", "Modify"))
        self.pb_delete_from_inactive.setText(_translate("Dialog", "Delete"))
